-- CreateTable
CREATE TABLE Client (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(191) NOT NULL,
    email VARCHAR(191) NOT NULL,
    status BOOLEAN NOT NULL,

    UNIQUE INDEX Client_email_key(email),
    PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE Asset (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(191) NOT NULL,
    value DOUBLE NOT NULL,
    clientId INTEGER NOT NULL,

    PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE Asset ADD CONSTRAINT Asset_clientId_fkey FOREIGN KEY (clientId) REFERENCES Client(id) ON DELETE RESTRICT ON UPDATE CASCADE;